MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/FAIR/20171220/X-101-32x8d"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_PER_BATCH: False
  ROI_HEADS:
    USE_FPN: True
    DETECTIONS_PER_IMG: 1000 # Don't know if this is correct for this dataset?
  ROI_BOX_HEAD:
    NUM_CLASSES: 4 #+1 for background
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
#  ROI_MASK_HEAD:
#    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
#    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
#    PREDICTOR: "MaskRCNNC4Predictor"
#    POOLER_RESOLUTION: 14
#    POOLER_SAMPLING_RATIO: 2
#    RESOLUTION: 28
#    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: False
DATASETS:
  TRAIN: ("UAVDT_2018_train_cocostyle",)
  TEST: ("UAVDT_2018_train_cocostyle","UAVDT_2018_test_cocostyle")
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.00125
  WEIGHT_DECAY: 0.0001
  STEPS: (159343, 212458) #0.66 , 0.88
  MAX_ITER: 241430 # 10 epoch
  # # steps. max iter - 1 epoch = # images / batch size
  # num images for UAVDT = 24143
  IMS_PER_BATCH: 1
OUTPUT_DIR: "/APL/ICCVResults/UAVDT/MaskRCNN-X-101-32x8d-FPN-10epoch-July7"