MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    # Fix FPN_POST_NMS_TOP_N_TRAIN bug
    FPN_POST_NMS_PER_BATCH: False
  ROI_HEADS:
    USE_FPN: True
    # increase b/c VisDrone may have more
    DETECTIONS_PER_IMG: 1000
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 11
#  ROI_MASK_HEAD:
#    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
#    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
#    PREDICTOR: "MaskRCNNC4Predictor"
#    POOLER_RESOLUTION: 14
#    POOLER_SAMPLING_RATIO: 2
#    RESOLUTION: 28
#    SHARE_BOX_FEATURE_EXTRACTOR: False
  # Remove mask part
  MASK_ON: False
DATASETS:
  TRAIN: ("visdrone_2018_det_train_cocostyle",)
  TEST: ("visdrone_2018_det_train_cocostyle","visdrone_2018_det_val_cocostyle")
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  # Modified for 1 GPU
  # Div LR by 8, multiply # iter x 8
  #BASE_LR: 0.02
  BASE_LR: 0.0025
  # TODO: make this smaller? Need to observe the loss
  # 6471 images in train set for VisDrone
  WEIGHT_DECAY: 0.0001
  # # steps. max iter - 1 epoch = # images / batch size
  STEPS: (21352, 28470) # Should be 0.66 and 0.88
  MAX_ITER: 32354 # 5 epochs
  IMS_PER_BATCH: 1
TEST:
  IMS_PER_BATCH: 1

# Try out float 16 bit
#DTYPE: float16

